### ISSUE TITLE
Clay pan chocolate recipe

### ISSUE THREAD

**Issue by Mrbysco** [Belgabor/AMTweaker#1]
I wanna add a recipe for the clay pan chocolate.
I wanna make it so a blue slimeball from tinkers construct into chocolate makes truffle..
Cant figure out how to do that...
Any help @Belgabor 

PS: love amtweaker

-Mrbysco

**Comment by Belgabor** [comment]
Currently that's not possible, but I'll take a look =)

**Comment by Belgabor** [comment]
Unfortunately the source item is hardcoded to Ganache and there is no API for covering in chocolate. Some of the source items for chocolate covered food are determined by ore dictionary, but not that one.

**Comment by Belgabor** [comment]
API is done, I'll see to add this soon.

**Comment by Belgabor** [comment]
Implemented in 0.4.
